### ISSUE TITLE
Update The Contact Us Button

### ISSUE THREAD

**Issue by DanishDanial03** [afiqsuradi/serveutm-one-stop-center#16]
Request to remove the discord button and put link to the github and facebook button 
facebook : icon={<a href="https://www.facebook.com/univteknologimalaysia/?locale=ms_MY" target="_blank" rel="noopener noreferrer"><MdFacebook size="28px" /></a>}
github : icon={
                        <a href="https://github.com/afiqsuradi/serveutm-one-stop-center" target="_blank" rel="noopener noreferrer">
                          <BsGithub size="28px" />
                        </a>
                      }

**Comment by Struxxzed** [comment]
Facebook:  icon={<a href="https://www.facebook.com/univteknologimalaysia/?locale=ms_MY" target="_blank" rel="noopener noreferrer"><MdFacebook size="28px" /></a>}
Github: icon={
                        <a href="https://github.com/afiqsuradi/serveutm-one-stop-center" target="_blank" rel="noopener noreferrer">
                          <BsGithub size="28px" />
                        </a>
                      }
