### ISSUE TITLE
Network issue

### ISSUE THREAD

**Issue by DanishDanial03** [afiqsuradi/serveutm-one-stop-center#41]
![Screenshot 2023-10-08 021217](https://github.com/afiqsuradi/serveutm-one-stop-center/assets/80710482/0622f7bb-42f7-42c8-a173-9bc491cbfa2b)
it said network error when press publish button even got full speed wifi and mobile hotspot

**Comment by afiqsuradi** [comment]
Fixed, error due to the server cant accept files that is too large
