### ISSUE TITLE
publish error

### ISSUE THREAD

**Issue by nazanezam** [afiqsuradi/serveutm-one-stop-center#48]
Error when trying to publish new gig. It would not load images uploaded.

**Comment by afiqsuradi** [comment]
need more information;
video, image, etc...

**Comment by afiqsuradi** [comment]
i saw this error on the server.
![image](https://github.com/afiqsuradi/serveutm-one-stop-center/assets/35418084/b9e8ffb5-334b-474e-8d53-ec83a80b8aa1)

mind give me data you entered that cause this issue?

**Comment by nazanezam** [comment]
uploaded one picture but received this error message![Screenshot_20231009-171740.png](https://github.com/afiqsuradi/serveutm-one-stop-center/assets/129735419/ae1a1db6-438a-4129-bc4c-3141b656fb9f)

**Comment by afiqsuradi** [comment]
yeah, there is an issue with mobile upload.

**Comment by afiqsuradi** [comment]
added image validation for gallery in ui-redo branch
